---
# task/prerequisites file for renew_nomad_certificates
- name: "Create directory {{ renew_nomad_certificates_config_dir }}"
  ansible.builtin.file:
    path: "{{ renew_nomad_certificates_config_dir }}"
    state: directory
    owner: "{{ renew_nomad_certificates_nomad_user }}"
    group: "{{ renew_nomad_certificates_nomad_group }}"
    mode: '0755'
  become: true

- name: "Create directory templates directory in {{ renew_nomad_certificates_config_dir }}"
  ansible.builtin.file:
    path: "{{ renew_nomad_certificates_config_dir }}/templates"
    state: directory
    owner: "{{ renew_nomad_certificates_nomad_user }}"
    group: "{{ renew_nomad_certificates_nomad_group }}"
    mode: '0755'
  become: true

- name: "Ensure certificate/key directory(ies) exist(s)"
  ansible.builtin.file:
    path: "{{item | dirname }}"
    state: directory
    owner: "{{ renew_nomad_certificates_nomad_user }}"
    group: "{{ renew_nomad_certificates_nomad_group }}"
    mode: '0755'
  loop:
    - "{{ renew_nomad_certificates_cert_dest }}"
    - "{{ renew_nomad_certificates_key_dest }}"
    - "{{ renew_nomad_certificates_ca_dest }}"
  become: true
