---
# handlers file for renew_nomad_certificates
- name: "Reload service file"
  ansible.builtin.systemd:
    daemon_reload: true
  listen: "systemctl-daemon-reload"

- name: "Enable nomad-certs service"
  ansible.builtin.service:
    name: nomad-certs
    enabled: true
  listen: "systemctl-enable-nomad-certs"

- name: "Start nomad-certs service"
  ansible.builtin.service:
    name: nomad-certs
    state: restarted
  listen: "systemctl-restart-nomad-certs"
  when: renew_nomad_certificates_start_service
