---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: "Create group nomad"
      ansible.builtin.group:
        name: "nomad"
        state: present

    - name: "Create user nomad"
      ansible.builtin.user:
        name: "nomad"
        group: "nomad"
        shell: /bin/false
        state: present
